exp_dir: "/pasteur/u/jeffheo/projects/nemo-cvpr2023-jeff/data/exps/jeff_tennis_swing/gear"
format: "release"
videos:
  root_dir: "/pasteur/u/jeffheo/projects/nemo-cvpr2023-jeff/data/videos/jeff/gear"
  names: ["tennis_swing.0"]
