exp_dir: "/pasteur/u/jeffheo/projects/nemo-cvpr2023-jeff/data/exps/jeff_tennis_swing/gear"
format: "release"
videos:
  root_dir: "/pasteur/u/jeffheo/projects/nemo-cvpr2023-jeff/data/videos/jeff/gear"
  names: ["tennis_swing.0", "tennis_swing.1", "tennis_swing.2", "tennis_swing.3", "tennis_swing.4", "tennis_swing.5"]
