DEBUG: false
DEBUG_FREQ: 5
LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'vibe'
OUTPUT_DIR: 'results/vibe_wo_3dpw'
NUM_WORKERS: 8
SEED_VALUE: -1
DATASET:
  SEQLEN: 16
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 300.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  D_MOTION_LOSS_W: 0.5
TRAIN:
  BATCH_SIZE: 32
  NUM_ITERS_PER_EPOCH: 500
  PRETRAINED: ''
  PRETRAINED_REGRESSOR: 'data/vibe_data/spin_model_checkpoint.pth.tar'
  RESUME: ''
  START_EPOCH: 0
  END_EPOCH: 30
  LR_PATIENCE: 5
  DATA_2D_RATIO: 0.6
  DATASETS_2D:
    - 'Insta'
#    - 'PoseTrack'
#    - 'PennAction'
  DATASETS_3D:
#    - 'ThreeDPW'
    - 'MPII3D'
  DATASET_EVAL: 'ThreeDPW'
  GEN_LR: 0.00005
  GEN_WD: 0.0
  MOT_DISCR:
    OPTIM: 'Adam'
    LR: 0.0001
    WD: 0.0001
    MOMENTUM: 0.9
    HIDDEN_SIZE: 1024
    NUM_LAYERS: 2
    FEATURE_POOL: 'attention'
    ATT:
      LAYERS: 3
      SIZE: 1024
      DROPOUT: 0.2
MODEL:
  TEMPORAL_TYPE: 'gru'
  TGRU:
    NUM_LAYERS: 2
    ADD_LINEAR: true
    RESIDUAL: true
    BIDIRECTIONAL: false
    HIDDEN_SIZE: 1024